---
collections:
  - name: community.general
    version: 5.8.10
  - name: community.sops
    version: 1.9.4
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 2.12.0
roles:
  - src: xanmanning.k3s
    version: v3.6.1
